#ifndef header_h
#define header_h

String file_head=
"<html>\r\n"
"	<head>\r\n"
"        <meta charset=\"utf-8\">\r\n"
"		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n"
"\r\n"
"		<!-- Bootstrap CSS -->\r\n"
"		<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n"
"\r\n"
"		<!-- Font CSS -->\r\n"
"   	<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\" integrity=\"sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/\" crossorigin=\"anonymous\">\r\n"
"\r\n"
"		<!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n"
"		<script src=\"https://code.jquery.com/jquery-3.4.0.min.js\"></script>\r\n"
"		<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n"
"		<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n"
"\r\n"
"		<title>ESP-01 IR</title>\r\n"
"	</head>\r\n";

String file_index_body=
"	<script type=\"text/javascript\">\r\n"
"                                  \r\n"
"		function ir_cmd(str_cmd){\r\n"
"			$.ajax({\r\n"
"				url: \"cmd\",\r\n"
"				type: 'GET',\r\n"
"				data: {n:str_cmd},\r\n"
"				success: function(response){\r\n"
"					var json = $.parseJSON(JSON.stringify(response));\r\n"
"					$('#stato').val(json[\"output\"]);\r\n"
"				},\r\n"
"				error: function(xhr){\r\n"
"				}\r\n"
"			});\r\n"
"		}\r\n"
"\r\n"
"	</script>\r\n"
"\r\n"
"	<body>\r\n"
"		<div class=\"container\">\r\n"
"			<div class=\"row\">\r\n"
"				<div class=\"py-5 col-md-12 text-center\">\r\n"
"					<div class=\"form-group\">\r\n"
"						<h1>ESP-01 IR</h1>\r\n"
"\r\n"
"						<div class=\"form-row justify-content-center\">\r\n"
"							<div class=\"py-3 input-group col-md-3\">\r\n"
"								<div class=\"input-group-prepend\">\r\n"
"									<span class=\"input-group-text mb-2 \" >STATO:</span>\r\n"
"								</div>\r\n"
"								<input id =\"stato\" type=\"text\" class=\"form-control\" aria-label=\"Sizing example input\" aria-describedby=\"inputGroup-sizing-sm\" readonly>\r\n"
"							</div>\r\n"
"						</div>\r\n"
"						<div class=\"py-3 col-md-12 text-center\">\r\n"
"							<button type=\"button\" onclick=\"ir_cmd('pwr')\" class=\"btn btn-primary btn-lg\">TEST</button>\r\n"
"\r\n"
"						</div>\r\n"
"					</div>\r\n"
"				</div>\r\n"
"			</div>\r\n"
"		</div>\r\n"
"	</body>\r\n"
"</html>\r\n";

String file_error_body=
" <body>\r\n"
"   <div class=\"container\">\r\n"
"     <div class=\"row\">\r\n"
"       <div class=\"py-5 col-md-12 text-center\">\r\n"
"         <div class=\"error-template\">\r\n"
"           <h1>Oops!</h1>\r\n"
"           <h2>404 Not Found</h2>\r\n"
"           <div class=\"error-details\">\r\n"
"               Scusi, si &egrave verificato un errore, la pagina richiesta non &egrave stata trovata!\r\n"
"             <br>\r\n"
"               %mex \n"
"           </div>\r\n"
"           <div class=\"error-actions py-4\">\r\n"
"             <a href=\"/\" class=\"btn btn-primary btn-lg\">\r\n"
"               Ritorna alla Home\r\n"
"             </a>\r\n"
"           </div>\r\n"
"         </div>\r\n"
"       </div>\r\n"
"     </div>\r\n"
"   </div>\r\n"
" </body>\r\n"
"</html>\r\n";

#endif

