#ifndef header_h
#define header_h

String file1=
"<html>\r\n"
"	<head>\r\n"
"        <meta charset=\"utf-8\">\r\n"
"		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n"
"\r\n"
"		<!-- Bootstrap CSS -->\r\n"
"		<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n"
"\r\n"
"		<!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n"
"		<script src=\"https://code.jquery.com/jquery-3.4.0.min.js\"></script>\r\n"
"		<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n"
"		<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n"
"\r\n"
"		<title>ESP-01 RELE</title>\r\n"
"	</head>\r\n"
"	<body>\r\n"
"		<div class=\"container\">\r\n"
"			<div class=\"row\">\r\n"
"				<div class=\"py-5 col-md-12 text-center\">\r\n"
"					<div class=\"form-group\">\r\n"
"						<h1>ESP-01 RELE</h1>\r\n"
"\r\n"
"						<div class=\"form-row justify-content-center\">\r\n"
"							<div class=\"py-3 input-group col-md-3\">\r\n"
"								<div class=\"input-group-prepend\">\r\n"
"									<span class=\"input-group-text mb-2 \" >STATO:</span>\r\n"
"								</div>\r\n"
"								<input type=\"text\" class=\"form-control\" aria-label=\"Sizing example input\" aria-describedby=\"inputGroup-sizing-sm\" readonly>\r\n"
"							</div>\r\n"
"						</div>\r\n"
"						<div class=\"py-3 col-md-12 text-center\">\r\n"
"							<a href=\"/cmd?n=on\" class=\"btn btn-primary btn-lg\">\r\n"
"								ON\r\n"
"							</a>\r\n"
"							<a href=\"/cmd?n=off\" class=\"btn btn-primary btn-lg\">\r\n"
"								OFF\r\n"
"							</a>\r\n"
"							<a href=\"/cmd?n=toggle\" class=\"btn btn-primary btn-lg\">\r\n"
"								TOGGLE\r\n"
"							</a>\r\n"
"							<a href=\"/cmd?n=stato_rele\" class=\"btn btn-primary btn-lg\">\r\n"
"								STATUS\r\n"
"							</a>\r\n"
"						</div>\r\n"
"					</div>\r\n"
"				</div>\r\n"
"			</div>\r\n"
"		</div>\r\n"
"	</body>\r\n"
"</html>\r\n";

#endif
