ALTER TABLE "TB_NET_DEVICE_TYPE" ADD COLUMN GOOGLE_TRAITS TEXT DEFAULT '-' NOT NULL;

echo "UPDATE TB_NET_DEVICE_TYPE SET GOOGLE_TYPE=\"action.devices.types.SWITCH\", GOOGLE_TRAITS=\"action.devices.traits.OnOff,\" WHERE 1=1;" > up.sql

echo "SELECT * FROM TB_NET_DEVICE_TYPE;" > select.sql

echo "SELECT NET_CODE, NET_MAC, GOOGLE_TYPE, GOOGLE_TRAITS FROM TB_NET_DEVICE, TB_NET_DEVICE_TYPE WHERE TB_NET_DEVICE.NET_TYPE = TB_NET_DEVICE_TYPE.TYPE_CODE;" > sel.sql